repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: gitleaks
        language: system
        args: ["detect","--baseline-path", "gitleaks-report.json","--verbose"]
